### ISSUE TITLE
github.com/hashicorp/go-msgpack - obsolete fork?

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/net-rpc-msgpackrpc#8]
Similar to #1 (still unfixed), these days, 6 years after the original report this issue is more valid than ever.

[github.com/hashicorp/go-msgpack](https://github.com/hashicorp/go-msgpack) is an unnecessary fork of actively maintained [github.com/ugorji/go](https://github.com/ugorji/go).  
I recommend to use the latter.

It would be even better if depending libraries just use `github.com/ugorji/go` directly and let this [obsolete library](https://github.com/hashicorp/net-rpc-msgpackrpc/issues/1#issuecomment-24591071) rest in peace.

**Comment by jefferai** [comment]
It's unclear what you are angling for here. Yes, this library is obsolete. But there are dependencies out there that still rely on it because they can't or won't switch to the other fork.

You are welcome not to use it, but we won't break those other dependencies by removing it. At some point we may archive it but do far it is useful to still be able to commit, such as when go modules came around.

**Comment by onlyjob** [comment]
If this library is still important then wouldn't it be worth caring for good dependency hygiene and software life cycle?

Why not switch to `github.com/ugorji/go`, as long as this library is useful? This way at least less redundant libraries will be used by larger projects and everyone will benefit from that.

Why resistance? Please reopen.

**Comment by jefferai** [comment]
Because it's not a drop in replacement. See https://github.com/hashicorp/consul/issues/6664
